# reproducibility
deterministic: False # 完全重复时，需要设置为True
random_seed: 42
use_exit: False
# training

pl_trainer:
  fast_dev_run: False # Enable this for debug purposes
  accelerator:  gpu
  devices: [0,1]
  strategy: ddp_find_unused_parameters_true
  precision: bf16-mixed  # 16-mixed
  # max_steps: 10000
  max_epochs: ${data.train_max_epochs}
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 0.5
  gradient_clip_algorithm: value
  profiler: simple
  log_every_n_steps: 10

monitor_metric: 'val_loss'
monitor_metric_mode: 'min'

early_stopping:
  patience: ${data.early_stopping_patience} # 60
  verbose: False

model_checkpoints:
  save_top_k: 3
  verbose: False
  save_last: True
  every_n_epochs: 50